services:
  code-server:
    container_name: code-server
    image: ghcr.io/fahmula/code-server:latest
    restart: unless-stopped
    ports:
      - "8455:8455"
    volumes:
      - /mnt/cache/appdata/code-server:/home/code/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    

